# Hotel Booking Analytics

## Data Loading and Initial Overview

### Objective

This notebook focuses on loading the Hotel Booking Demand dataset and performing an initial assessment of its structure, dimensions, data types, and overall quality. The objective is to understand the dataset before any preprocessing or exploratory analysis.

In [13]:
## Import Required Libraries

In [14]:
import warnings
warnings.filterwarnings("ignore")

In [15]:
import numpy as np 
import pandas as pd

In [16]:
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

plt.style.use("default")

## Load Dataset

In [17]:
df = pd.read_csv("../data/hotel_bookings.csv")

In [18]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## Dataset Shape

In [8]:
rows, columns = df.shape 
print(f"Number of Rows : {rows}")
print(f"Number of Columns : {columns}")

Number of Rows : 119390
Number of Columns : 32

## Dataset Information

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [19]:
## Statistical Summary

In [20]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,119390,2,City Hotel,79330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,119390.0,NaN,NaN,NaN,0.370416,0.482918,0.0,0.0,0.0,1.0,1.0
lead_time,119390.0,NaN,NaN,NaN,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
arrival_date_year,119390.0,NaN,NaN,NaN,2016.156554,0.707476,2015.0,2016.0,2016.0,2017.0,2017.0
arrival_date_month,119390,12,August,13877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,119390.0,NaN,NaN,NaN,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
arrival_date_day_of_month,119390.0,NaN,NaN,NaN,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
stays_in_weekend_nights,119390.0,NaN,NaN,NaN,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
stays_in_week_nights,119390.0,NaN,NaN,NaN,2.500302,1.908286,0.0,1.0,2.0,3.0,50.0
adults,119390.0,NaN,NaN,NaN,1.856403,0.579261,0.0,2.0,2.0,2.0,55.0
children,119386.0,NaN,NaN,NaN,0.10389,0.398561,0.0,0.0,0.0,0.0,10.0
babies,119390.0,NaN,NaN,NaN,0.007949,0.097436,0.0,0.0,0.0,0.0,10.0
meal,119390,5,BB,92310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,118902,177,PRT,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,119390,8,Online TA,56477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,119390,5,TA/TO,97870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,119390.0,NaN,NaN,NaN,0.031912,0.175767,0.0,0.0,0.0,0.0,1.0
previous_cancellations,119390.0,NaN,NaN,NaN,0.087118,0.844336,0.0,0.0,0.0,0.0,26.0
previous_bookings_not_canceled,119390.0,NaN,NaN,NaN,0.137097,1.497437,0.0,0.0,0.0,0.0,72.0
reserved_room_type,119390,10,A,85994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,119390,12,A,74053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,119390.0,NaN,NaN,NaN,0.221124,0.652306,0.0,0.0,0.0,0.0,21.0
deposit_type,119390,3,No Deposit,104641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent,103050.0,NaN,NaN,NaN,86.693382,110.774548,1.0,9.0,14.0,229.0,535.0
company,6797.0,NaN,NaN,NaN,189.266735,131.655015,6.0,62.0,179.0,270.0,543.0
days_in_waiting_list,119390.0,NaN,NaN,NaN,2.321149,17.594721,0.0,0.0,0.0,0.0,391.0
customer_type,119390,4,Transient,89613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,119390.0,NaN,NaN,NaN,101.831122,50.53579,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,NaN,NaN,NaN,0.062518,0.245291,0.0,0.0,0.0,0.0,8.0
total_of_special_requests,119390.0,NaN,NaN,NaN,0.571363,0.792798,0.0,0.0,0.0,1.0,5.0
reservation_status,119390,3,Check-Out,75166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,119390,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
## First Five Records

In [22]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [23]:
## Last Five Records

In [24]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

## Dataset Profiling

This section provides a high-level overview of the dataset, including the list of features, data types, missing values, duplicate records, and memory usage. These checks help identify potential data quality issues before preprocessing.

In [26]:
#Display Column Names 
df.columns.tolist()

['hotel',
 'is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_month',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'reserved_room_type',
 'assigned_room_type',
 'booking_changes',
 'deposit_type',
 'agent',
 'company',
 'days_in_waiting_list',
 'customer_type',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests',
 'reservation_status',
 'reservation_status_date']

In [27]:
#Check Data Types
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [28]:
#Missing Values

In [29]:
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing_values = missing_values[missing_values["Missing Values"] > 0]
missing_values.sort_values("Percentage", ascending=False)

          Missing Values  Percentage
company           112593   94.306893
agent              16340   13.686238
country              488    0.408744
children               4    0.003350

In [30]:
#Duplicate Records

In [31]:
print(f"Duplicate Records : {df.duplicated().sum()}")

Duplicate Records : 31994

In [32]:
#Memory Usage

In [33]:
memory = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Memory Usage : {memory:.2f} MB")

Memory Usage : 93.90 MB

In [35]:
#Numerical Features
numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Number of Numerical Features :", len(numerical_columns))
numerical_columns

Number of Numerical Features : 20

['is_canceled',
 'lead_time',
 'arrival_date_year',
 'arrival_date_week_number',
 'arrival_date_day_of_month',
 'stays_in_weekend_nights',
 'stays_in_week_nights',
 'adults',
 'children',
 'babies',
 'is_repeated_guest',
 'previous_cancellations',
 'previous_bookings_not_canceled',
 'booking_changes',
 'agent',
 'company',
 'days_in_waiting_list',
 'adr',
 'required_car_parking_spaces',
 'total_of_special_requests']

In [36]:
#Categorical Features
categorical_columns = df.select_dtypes(include="object").columns.tolist()

print("Number of Categorical Features :", len(categorical_columns))
categorical_columns

Number of Categorical Features : 12

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status',
 'reservation_status_date']

In [37]:
#Unique Values
pd.DataFrame({
    "Unique Values": df.nunique()
}).sort_values("Unique Values", ascending=False)

                                Unique Values
adr                                      8879
reservation_status_date                   926
lead_time                                 479
company                                   352
agent                                     333
country                                   177
days_in_waiting_list                      128
previous_bookings_not_canceled             73
arrival_date_week_number                   53
stays_in_week_nights                       35
arrival_date_day_of_month                  31
booking_changes                            21
stays_in_weekend_nights                    17
previous_cancellations                     15
adults                                     14
arrival_date_month                         12
assigned_room_type                         12
reserved_room_type                         10
market_segment                              8
total_of_special_requests                   6
distribution_channel                        5
meal                                        5
babies                                      5
children                                    5
required_car_parking_spaces                 5
customer_type                               4
reservation_status                          3
deposit_type                                3
arrival_date_year                           3
hotel                                       2
is_canceled                                 2
is_repeated_guest                           2

In [39]:
#Random Sample
df.sample(5, random_state=42)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
30946,Resort Hotel,0,203,2016,December,49,2,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,4,No Deposit,250.0,NaN,0,Transient,66.8,0,0,Check-Out,2016-12-09
40207,City Hotel,1,82,2015,July,29,16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,76.5,0,0,Canceled,2015-07-16
103708,City Hotel,0,25,2016,December,53,27,0,3,3,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,K,2,No Deposit,220.0,NaN,0,Transient-Party,60.0,0,1,Check-Out,2016-12-30
85144,City Hotel,0,1,2016,March,11,9,0,1,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient-Party,95.0,0,0,Check-Out,2016-03-10
109991,City Hotel,0,70,2017,April,16,16,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,108.0,0,0,Check-Out,2017-04-20

## Initial Data Quality Assessment

This section evaluates the overall quality of the dataset by examining missing values, duplicate records, and feature types. Understanding these characteristics is essential before performing data cleaning and exploratory analysis.

In [40]:
#Check Missing Values
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage (%)": round((df.isnull().sum() / len(df)) * 100, 2)
})

missing_values = missing_values[missing_values["Missing Values"] > 0]
missing_values.sort_values(by="Percentage (%)", ascending=False)

          Missing Values  Percentage (%)
company           112593           94.31
agent              16340           13.69
country              488            0.41
children               4            0.00

In [41]:
#Check Duplicate Records
duplicate_count = df.duplicated().sum()

print(f"Total Duplicate Records: {duplicate_count}")

Total Duplicate Records: 31994

In [42]:
#Feature Classification

In [43]:
numerical_features = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = df.select_dtypes(include=["object"]).columns.tolist()

print(f"Number of Numerical Features   : {len(numerical_features)}")
print(f"Number of Categorical Features : {len(categorical_features)}")

Number of Numerical Features   : 20
Number of Categorical Features : 12

In [44]:
#Display Feature Lists

In [45]:
print("Numerical Features:\n")
print(numerical_features)

Numerical Features:

['is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']

In [46]:
print("Categorical Features:\n")
print(categorical_features)

Categorical Features:

['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type', 'reservation_status', 'reservation_status_date']

In [47]:
#Unique Values in Each Feature

In [48]:
unique_values = pd.DataFrame({
    "Feature": df.columns,
    "Unique Values": df.nunique().values
})

unique_values.sort_values(by="Unique Values", ascending=False)

                           Feature  Unique Values
27                             adr           8879
31         reservation_status_date            926
2                        lead_time            479
24                         company            352
23                           agent            333
13                         country            177
25            days_in_waiting_list            128
18  previous_bookings_not_canceled             73
5         arrival_date_week_number             53
8             stays_in_week_nights             35
6        arrival_date_day_of_month             31
21                 booking_changes             21
7          stays_in_weekend_nights             17
17          previous_cancellations             15
9                           adults             14
4               arrival_date_month             12
20              assigned_room_type             12
19              reserved_room_type             10
14                  market_segment              8
29       total_of_special_requests              6
15            distribution_channel              5
12                            meal              5
11                          babies              5
10                        children              5
28     required_car_parking_spaces              5
26                   customer_type              4
30              reservation_status              3
22                    deposit_type              3
3                arrival_date_year              3
0                            hotel              2
1                      is_canceled              2
16               is_repeated_guest              2

In [49]:
#Random Sample

In [50]:
df.sample(5, random_state=42)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
30946,Resort Hotel,0,203,2016,December,49,2,2,5,2,0.0,0,BB,GBR,Direct,Direct,0,0,0,F,F,4,No Deposit,250.0,NaN,0,Transient,66.8,0,0,Check-Out,2016-12-09
40207,City Hotel,1,82,2015,July,29,16,0,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,76.5,0,0,Canceled,2015-07-16
103708,City Hotel,0,25,2016,December,53,27,0,3,3,0.0,0,BB,BRA,Offline TA/TO,TA/TO,0,0,0,A,K,2,No Deposit,220.0,NaN,0,Transient-Party,60.0,0,1,Check-Out,2016-12-30
85144,City Hotel,0,1,2016,March,11,9,0,1,1,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient-Party,95.0,0,0,Check-Out,2016-03-10
109991,City Hotel,0,70,2017,April,16,16,2,2,2,0.0,0,SC,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,108.0,0,0,Check-Out,2017-04-20

## Summary

The dataset has been successfully loaded and examined. The initial assessment provided information about its dimensions, data types, missing values, duplicate records, and feature categories.